### ISSUE TITLE
Using KNN Imputer to fill the missing values

### ISSUE THREAD

**Issue by sreedharjinka** [sreedharjinka/Thyroid-DetectionG97#6]

**Comment by Dhruv69408012** [comment]
The KNN imputer is a module within the impute package of the sklearn module of python. The imputer fills in missing values based on the given number of nearest values which have similar attributes. The imputer was only capable of accepting missing values in the form of nan values in the numpy module of python but in the data set the missing values were indicated using "?" hence they were first converted to nan values in numpy module. After this the true and false values coded as "t" and "f" hence they were converted to TRUE and FALSE. The final problem was with the gender where male was coded as "M" and female was coded as "F". Since the imputer did not accept them they were converted to 1 for male and 0 for female. Then the number of neighbors was set to 5 and the data was imputed using the code attached as a text file. The dataset before and after imputation is also attached.
[code.txt](https://github.com/sreedharjinka/Thyroid-DetectionG97/files/13237793/code.txt)
[imputed data.csv](https://github.com/sreedharjinka/Thyroid-DetectionG97/files/13237795/imputed.data.csv)
[dataset.csv](https://github.com/sreedharjinka/Thyroid-DetectionG97/files/13237903/dataset.csv)
